import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

import { Roboto } from "next/font/google";

import "@/app/globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { Navbar } from "@/components/layout/Navbar";
import { MobileProvider } from "@/contexts/MobileContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} className="bg-bg-primary dark:bg-bg-dark">
      <body
        className={`${roboto.variable} antialiased bg-white dark:bg-gray-900`}
      >
        <NextIntlClientProvider>
          <ThemeProvider>
            <MobileProvider>
              <div className="bg-bg-primary dark:bg-bg-dark text-text-primary dark:text-text-dark transition-colors duration-300 ">
                <Navbar />
                {children}
              </div>
            </MobileProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
