import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import { Roboto } from "next/font/google";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { MobileProvider } from "@/contexts/MobileContext";

import "@/app/globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//layout raiz que envolve toda a aplicação
export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} className="bg-bg-primary dark:bg-bg-dark">
      <body
        className={`${roboto.variable} antialiased bg-white dark:bg-gray-900`}
      >
        <NextIntlClientProvider locale={locale}>
          <ThemeProvider>
            <MobileProvider>{children}</MobileProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
